"""Agent 3 - Karate Scaffold Generator.

Three sub-commands:

    scaffold from-openapi --spec docs/openapi/claims-api.yaml --tag claims
    scaffold from-rule    --rule FRAUD_DUPLICATE_CLAIM
    scaffold suggest

All output lands in ``generated/features/`` (gitignored). The SDET
reviews drafts and copies anything worth keeping into
``src/test/resources/features/`` by hand. The agent itself NEVER writes
into ``src/test/`` directly - this is enforced by the path constants in
``_common/paths.py``.

LLM enrichment is opt-in (``LLM_ENABLED=true``). The deterministic
fallback is template-based and produces feature files that compile and
run against the live server.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

import yaml

from ._common import paths
from ._common import printer as p


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_HEADER = """\
# Generated by `python -m tools.cli scaffold {sub}`.
# DO NOT promote this file directly to src/test/resources/features/.
# Review it, edit assertions to match real behaviour, then copy by hand.
"""


def _load_openapi(spec_path: Path) -> dict:
    return yaml.safe_load(spec_path.read_text(encoding="utf-8"))


def _example_for(schema: dict, components: dict, depth: int = 0) -> Any:
    """Best-effort example value for a JSON-Schema-ish node."""
    if depth > 6:
        return None
    if "$ref" in schema:
        ref = schema["$ref"].split("/")[-1]
        target = components.get("schemas", {}).get(ref)
        if not target:
            return None
        return _example_for(target, components, depth + 1)
    if "example" in schema:
        return schema["example"]
    t = schema.get("type")
    if t == "object" or "properties" in schema:
        out: dict[str, Any] = {}
        props = schema.get("properties", {})
        required = set(schema.get("required", []))
        for name, sub in props.items():
            if required and name not in required:
                continue
            out[name] = _example_for(sub, components, depth + 1)
        return out
    if t == "array":
        return [_example_for(schema.get("items", {}), components, depth + 1)]
    if t == "integer":
        return schema.get("minimum", 1)
    if t == "number":
        return schema.get("minimum", 0)
    if t == "boolean":
        return True
    if t == "string":
        if schema.get("enum"):
            return schema["enum"][0]
        if schema.get("format") == "date":
            return "2026-04-10"
        if schema.get("format") == "date-time":
            return "2026-04-10T00:00:00.000Z"
        return "synthetic"
    return None


def _safe_filename(s: str) -> str:
    s = re.sub(r"[^A-Za-z0-9_\-]+", "_", s.strip("/"))
    return re.sub(r"_+", "_", s).strip("_") or "scaffold"


def _path_to_url_template(path: str) -> tuple[str, list[str]]:
    """Convert /api/claims/{id}/submit into ('/api/claims/' + id + '/submit', ['id']).

    Returns the Karate-DSL URL expression and the ordered list of path
    parameter names so the renderer can emit ``* def id = 'TODO'`` lines.
    """
    parts = re.split(r"(\{[^}]+\})", path)
    chunks: list[str] = []
    params: list[str] = []
    for part in parts:
        if not part:
            continue
        if part.startswith("{") and part.endswith("}"):
            name = part[1:-1]
            chunks.append(name)
            params.append(name)
        else:
            chunks.append(repr(part))
    return " + ".join(chunks), params


# ---------------------------------------------------------------------------
# from-openapi
# ---------------------------------------------------------------------------

@dataclass
class _OperationDraft:
    method: str
    path: str
    operation_id: str
    summary: str
    request_example: Any
    success_status: str
    error_statuses: list[str]
    requires_auth: bool


def _operations(spec: dict) -> list[_OperationDraft]:
    components = spec.get("components", {})
    out: list[_OperationDraft] = []
    for raw_path, ops in (spec.get("paths") or {}).items():
        if not isinstance(ops, dict):
            continue
        for method, op in ops.items():
            if method.lower() not in {"get", "post", "put", "patch", "delete"}:
                continue
            if not isinstance(op, dict):
                continue
            request_example = None
            req_body = op.get("requestBody")
            if isinstance(req_body, dict):
                schema = (
                    req_body.get("content", {})
                    .get("application/json", {})
                    .get("schema")
                )
                if schema:
                    request_example = _example_for(schema, components)
            responses = op.get("responses") or {}
            success = next(
                (code for code in responses if str(code).startswith("2")),
                "200",
            )
            errors = [c for c in responses if str(c).startswith(("4", "5"))]
            requires_auth = bool(op.get("security", [{"bearerAuth": []}])) and not (
                op.get("security") == []
            )
            op_id = op.get("operationId") or _safe_filename(f"{method}_{raw_path}")
            out.append(
                _OperationDraft(
                    method=method.upper(),
                    path=raw_path,
                    operation_id=op_id,
                    summary=op.get("summary", "").strip(),
                    request_example=request_example,
                    success_status=str(success),
                    error_statuses=[str(c) for c in errors],
                    requires_auth=requires_auth,
                )
            )
    return out


def _render_operation_feature(op: _OperationDraft, tag: str) -> str:
    body_block = ""
    if op.method in {"POST", "PUT", "PATCH"} and op.request_example is not None:
        pretty = json.dumps(op.request_example, indent=2, default=str)
        # Indent so the JSON aligns under `request`.
        pretty = "\n".join("      " + line for line in pretty.splitlines())
        body_block = f'    And request\n      """\n{pretty}\n      """\n'
    url_expr, path_params = _path_to_url_template(op.path)
    auth_block = (
        "    * call read('classpath:features/_common/reset.feature')\n"
        "    * configure headers = headers\n"
        if op.requires_auth
        else ""
    )
    # Placeholder defs for every path parameter so the draft compiles
    # before the SDET fills in real ids.
    param_defs = "".join(
        f"    * def {name} = 'TODO-{name.upper()}'\n" for name in path_params
    )

    method_call = op.method.lower()
    error_scenarios = ""
    if op.requires_auth and "401" in op.error_statuses:
        error_scenarios += (
            "\n  Scenario: 401 without bearer token\n"
            "    * configure headers = { Accept: 'application/json' }\n"
            + param_defs
            + f"    Given url baseUrl + {url_expr}\n"
            f"    When method {method_call}\n"
            "    Then status 401\n"
            "    And match response.error.code == 'UNAUTHORIZED'\n"
        )
    if "404" in op.error_statuses and path_params:
        # Substitute the first path parameter with a known-missing id.
        bad_url = url_expr.replace(path_params[0], f"'NOT-FOUND-{path_params[0].upper()}'", 1)
        error_scenarios += (
            "\n  Scenario: 404 for an unknown id\n"
            f"    Given url baseUrl + {bad_url}\n"
            f"    When method {method_call}\n"
            "    Then status 404\n"
            "    And match response.error.code == 'NOT_FOUND'\n"
        )

    return f"""{_HEADER.format(sub='from-openapi')}
@scaffold @{tag} @generated
Feature: {op.method} {op.path} - {op.summary or op.operation_id}

  Background:
{auth_block.rstrip() or '    # no auth required'}

  Scenario: positive ({op.success_status})
{param_defs}    Given url baseUrl + {url_expr}
{body_block}    When method {method_call}
    Then status {op.success_status}
{error_scenarios}"""


def from_openapi(
    spec: Optional[str] = None,
    tag: str = "claims",
    out: Optional[str] = None,
) -> int:
    spec_path = Path(spec) if spec else paths.OPENAPI_SPEC
    if not spec_path.is_file():
        p.fail(f"OpenAPI spec not found: {spec_path}")
        return 2
    out_dir = paths.ensure_dir(Path(out) if out else paths.GENERATED_FEATURES) / tag
    out_dir.mkdir(parents=True, exist_ok=True)

    p.hr(f"Scaffold from OpenAPI: {spec_path.name}  ->  {paths.safe_rel(out_dir)}/")
    spec_data = _load_openapi(spec_path)
    drafts = _operations(spec_data)
    if not drafts:
        p.warn("No operations found in spec.")
        return 1
    written = 0
    for op in drafts:
        feature = _render_operation_feature(op, tag=tag)
        # Operation ids from auto-generation already encode method + path
        # (e.g. "post_/api/claims"). Don't double-prefix when sanitising.
        base = op.operation_id
        if not base.lower().startswith(op.method.lower()):
            base = f"{op.method.lower()}_{base}"
        fname = _safe_filename(base) + ".feature"
        target = out_dir / fname
        target.write_text(feature, encoding="utf-8")
        written += 1
    p.ok(f"Generated {written} draft feature(s) under {paths.safe_rel(out_dir)}/")
    p.warn("Review carefully. The SDET copies into src/test/resources/features/ by hand.")
    return 0


# ---------------------------------------------------------------------------
# from-rule
# ---------------------------------------------------------------------------

# Templates per rule code. Each template includes one positive trigger
# scenario and one guardrail (false-positive) scenario, anchored on the
# seeded MBR-00010..MBR-00012 / CLM-00050..CLM-00053 fixtures.

_RULE_TEMPLATES: dict[str, str] = {}


def _register_rule(code: str, body: str) -> None:
    _RULE_TEMPLATES[code] = body


_register_rule(
    "FRAUD_DUPLICATE_CLAIM",
    """\
Background:
    * call read('classpath:features/_common/reset.feature')
    * configure headers = headers

  Scenario: positive - exact rebill of CLM-00050 fires DENY
    Given url baseUrl + '/api/claims'
    And request
      \"\"\"
      { memberId: 'MBR-00010', providerId: 'PRV-00001', encounterId: 'ENC-00010',
        payerId: 'PAYER-A', serviceDate: '2026-03-01',
        lines: [ { procedureCode: 'PROC-OFFICE-VISIT-1', units: 1, billedAmount: 100.0 } ] }
      \"\"\"
    When method post
    Then status 201
    * def claimId = response.claimId
    Given url baseUrl + '/api/claims/' + claimId + '/submit'
    When method post
    Then status 200
    And match response.adjudication.status == 'DENIED'
    And match response.adjudication.winningAction == 'DENY'

  Scenario: guardrail - same DOS but different procedure does NOT fire
    Given url baseUrl + '/api/claims'
    And request
      \"\"\"
      { memberId: 'MBR-00010', providerId: 'PRV-00001', encounterId: 'ENC-00010',
        payerId: 'PAYER-A', serviceDate: '2026-03-01',
        lines: [ { procedureCode: 'PROC-LAB-CBC', units: 1, billedAmount: 30.0 } ] }
      \"\"\"
    When method post
    Then status 201
    * def claimId = response.claimId
    Given url baseUrl + '/api/claims/' + claimId + '/submit'
    When method post
    Then status 200
    And match response.adjudication.winningAction == 'APPROVE'
""",
)

_register_rule(
    "FRAUD_PHANTOM_BILLING",
    """\
Background:
    * call read('classpath:features/_common/reset.feature')
    * configure headers = headers

  Scenario: positive - claim without encounter fires DENY
    Given url baseUrl + '/api/claims'
    And request
      \"\"\"
      { memberId: 'MBR-00010', providerId: 'PRV-00001',
        payerId: 'PAYER-A', serviceDate: '2026-04-15',
        lines: [ { procedureCode: 'PROC-OFFICE-VISIT-1', units: 1, billedAmount: 100.0 } ] }
      \"\"\"
    When method post
    Then status 201
    * def claimId = response.claimId
    Given url baseUrl + '/api/claims/' + claimId + '/submit'
    When method post
    Then status 200
    And match response.adjudication.winningAction == 'DENY'

  Scenario: guardrail - claim with a valid encounter pays
    # See features/happy/claim_lifecycle.feature.
""",
)


def _slug(rule: str) -> str:
    return rule.lower().replace("_", "-")


def from_rule(
    rule: Optional[str] = None,
    out: Optional[str] = None,
) -> int:
    if not rule:
        p.fail("--rule is required (e.g. FRAUD_DUPLICATE_CLAIM)")
        return 2
    code = rule.strip().upper()
    if code not in _RULE_TEMPLATES:
        p.fail(f"No template registered for rule {code}")
        p.warn("Templates are deliberately limited to the most-asked rules; "
               "the rest stay as `from-openapi` scaffolds. Edit "
               "tools/agents/karate_scaffold.py to add more.")
        return 3
    out_dir = paths.ensure_dir(Path(out) if out else paths.GENERATED_FEATURES) / "rules"
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / f"{_slug(code)}.feature"
    body = _RULE_TEMPLATES[code]
    text = (
        f"{_HEADER.format(sub='from-rule')}"
        f"@generated @rules @{code.split('_', 1)[0].lower()}\n"
        f"Feature: {code} (generated draft)\n\n"
        f"  {body}"
    )
    target.write_text(text, encoding="utf-8")
    p.hr(f"Scaffold from rule: {code}")
    p.ok(f"Wrote {paths.safe_rel(target)}")
    p.warn("Review and copy by hand into src/test/resources/features/<category>/<rule>.feature.")
    return 0


# ---------------------------------------------------------------------------
# suggest (coverage gap)
# ---------------------------------------------------------------------------

_RULE_CODES = (
    "FRAUD_DUPLICATE_CLAIM",
    "FRAUD_PHANTOM_BILLING",
    "FRAUD_INVALID_PROVIDER",
    "ABUSE_UPCODING",
    "ABUSE_EXCESSIVE_FREQUENCY",
    "ABUSE_UNBUNDLING",
    "WASTE_DUPLICATE_SERVICE",
    "WASTE_MEDICALLY_UNLIKELY_UNITS",
    "WASTE_UNNECESSARY_PATTERN",
)


def _scan_features_for_codes() -> dict[str, list[str]]:
    """Return rule -> [feature paths that mention it]."""
    coverage: dict[str, list[str]] = {c: [] for c in _RULE_CODES}
    if not paths.KARATE_FEATURES.exists():
        return coverage
    for feature in paths.KARATE_FEATURES.rglob("*.feature"):
        text = feature.read_text(encoding="utf-8", errors="replace")
        rel = feature.relative_to(paths.ROOT).as_posix()
        for code in _RULE_CODES:
            if code in text:
                coverage[code].append(rel)
    return coverage


def suggest() -> int:
    coverage = _scan_features_for_codes()
    paths.ensure_dir(paths.REPORTS_DIR)
    target = paths.REPORTS_DIR / "test-generation-plan.md"
    lines = ["# Test Generation Plan", ""]
    lines.append("Coverage matrix between the 9 catalogued rule codes and the\n"
                 "Karate features under `src/test/resources/features/`:\n")
    lines.append("| Rule code | Coverage | Mentioned in |")
    lines.append("|---|---|---|")
    uncovered: list[str] = []
    for code, hits in coverage.items():
        if hits:
            lines.append(f"| `{code}` | OK | {', '.join(f'`{h}`' for h in hits)} |")
        else:
            uncovered.append(code)
            lines.append(f"| `{code}` | **MISSING** | _(no scenario references this code)_ |")
    if uncovered:
        lines.append("")
        lines.append("## Suggested next actions")
        lines.append("")
        for code in uncovered:
            lines.append(f"- Run `python -m tools.cli scaffold from-rule --rule {code}` to draft a starting feature.")
    else:
        lines.append("")
        lines.append("All 9 rule codes appear in at least one Karate feature.")
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    p.hr("Coverage suggestion")
    p.ok(f"Wrote {paths.safe_rel(target)}")
    if uncovered:
        p.warn(f"Missing rule coverage: {', '.join(uncovered)}")
    else:
        p.ok("All 9 rule codes covered.")
    return 0
